In [26]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

In [31]:
import numpy as np

y = np.array(['cat', 'dog', 'cat', 'bird'])

In [32]:
y

array(['cat', 'dog', 'cat', 'bird'], dtype='<U4')

In [33]:
import pandas as pd 

Y = pd.DataFrame(y)
Y

0
0   cat
1   dog
2   cat
3  bird

In [4]:
le.transform(y)

NotFittedError: This LabelEncoder instance is not fitted yet. Call 'fit' with appropriate arguments before using this estimator.

In [31]:
arr = np.unique(np.sort(y))
d={}
for i,j in enumerate(arr):
    d[j]=i
d

{'bird': 0, 'cat': 1, 'dog': 2}

In [5]:
le.fit_transform(y)

array([1, 2, 1, 0], dtype=int64)

In [6]:
le.classes_

array(['bird', 'cat', 'dog'], dtype='<U4')

In [16]:
le.inverse_transform(np.array([1, 2]))

array(['cat', 'dog'], dtype='<U4')

In [17]:
le.inverse_transform([1, 2])

array(['cat', 'dog'], dtype='<U4')

In [22]:
le.fit(y)

LabelEncoder()

In [34]:
class LabelEncoder:
    def fit(self, y):
        if (y.ndim==1) or (y.ndim==2 and y.shape[1]==1):
            arr = np.unique(np.sort(y))
            self.d={}
            for i,j in enumerate(arr):
                self.d[j]=i
            return self
        else:
            raise ValueError("y should be a 1d array, got an array of shape {} instead".format(y.shape))
            
    
    def transform(self, y):
        return np.vectorize(self._encode_value)(y)
    
    def _encode_value(self, value):
        try:
            return self.d.get(value, -1)  
        except:
            raise Exception("This instance of encoder is not fitted yet")
            
    def fit_transform(self, y):
        self.fit(y)
        self.transform(y)
        
    def _reverse_dict(self):
        try:
            return {value: key for key, value in self.d.items()}
        except:
            raise Exception("This instance of encoder is not fitted yet")
    
    def inverse_transform(self, y):
        self.d = self._reverse_dict()
        return np.vectorize(self._encode_value)(y)

In [35]:
le = LabelEncoder()

In [36]:
le.fit(Y)

In [37]:
le.transform(Y)

array([[1],
       [2],
       [1],
       [0]])

In [79]:
le.inverse_transform([0,1,2])

array(['bird', 'cat', 'dog'], dtype='<U4')

In [29]:
arr = np.array([['cat', 'f'],['dog','m'],['bird','f']])
arr

array([['cat', 'f'],
       ['dog', 'm'],
       ['bird', 'f']], dtype='<U4')

In [30]:
LabelEncoder().fit_transform(arr)

ValueError: y should be a 1d array, got an array of shape (3, 2) instead

In [17]:
le.fit_transform(arr)

In [14]:
from sklearn.preprocessing import OrdinalEncoder

In [16]:
oe = OrdinalEncoder()
oe.fit_transform(arr)

array([[1., 0.],
       [2., 1.],
       [0., 0.]])

In [ ]:
class 

In [18]:
y.shape

(4,)

In [22]:
y.ndim

1

In [23]:
    print('yes')

yes
